spring:
  datasource:
    url: ${datasource}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${username}
    password: ${password}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  security:
    oauth2.client:
      registration:
        google:
          clientId: ${client_id}
          clientSecret: ${client_secret}
          scope:
            - email
            - profile

cors:
  allowed-origins: 'http://localhost:3000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

# jwt secret key 설정
jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  secret: ${jwt_secret}
  token-validity-in-seconds: 1800 # 30분
  refresh-token-validity-in-seconds: 1209600  # 20160분, 2주

# 토큰 관련 secret Key 및 RedirectUri 설정
app:
  auth:
    tokenSecret: ${token_secret}
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect

logging:
  level:
    org.hibernate:
      type.descriptor.sql: debug
      SQL: DEBUG